### ISSUE TITLE
Fix issue with Vagrant and settings files.

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#570]
Vagrant is still not properly copying the deploy settings file. Therefore, every time a nutch crawl is run there are failures. There needs to be a fix to this.

**Comment by brittainhard** [comment]
Current issue:

```
          ID: /vagrant/source/memex/settings.py
    Function: file.copy
      Result: True
     Comment: The target file "/vagrant/source/memex/settings.py" exists and will not be overwritten
     Started: 17:29:25.363369
    Duration: 6.775 ms
     Changes:  
```
